server:
  port: ${PORT:4004}

auth:
  service:
    url: ${AUTH_SERVICE_URL}

spring:
  cloud:
    gateway:
      routes:

        # ---------------- PATIENT ----------------
        - id: patient-service
          uri: ${PATIENT_SERVICE_URL}
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # ---------------- AUTH ----------------
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # ---------------- API DOCS PATIENT ----------------
        - id: api-docs-patient-route
          uri: ${PATIENT_SERVICE_URL}
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        # ---------------- API DOCS AUTH ----------------
        - id: api-docs-auth-route
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

        # ---------------- CYCLE ----------------
        - id: cycle-tracker-cycles
          uri: ${CYCLE_SERVICE_URL}
          predicates:
            - Path=/api/cycles/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # ---------------- AI INSIGHTS ----------------
        - id: cycle-tracker-ai
          uri: ${CYCLE_SERVICE_URL}
          predicates:
            - Path=/api/ai/insights/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # ---------------- HEALTH PROFILE ----------------
        - id: cycle-tracker-health
          uri: ${CYCLE_SERVICE_URL}
          predicates:
            - Path=/api/health-profile/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # ---------------- SYMPTOMS ----------------
        - id: cycle-tracker-symptoms
          uri: ${CYCLE_SERVICE_URL}
          predicates:
            - Path=/api/symptoms/**
          filters:
            - StripPrefix=1
            - JwtValidation