spring.application.name=cycle-tracker-service
server.port=4006
spring.datasource.url=jdbc:postgresql://cycle-tracker-db:5432/cycle_tracker_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
# IMPORTANT: We manage schema via data.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=
gemini.api.key=AIzaSyCVamdUyql8YkbiIbhydmMm0jvqlerF3Hg

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=always
spring.web.error.include-exception=true


spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=cycle-tracker-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer