spring.application.name=patient-service
# PostgreSQL Datasource

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always


spring.kafka.bootstrap-servers=${KAFKA_URL}
spring.kafka.properties.security.protocol=SSL
spring.kafka.properties.ssl.keystore.type=PEM
spring.kafka.properties.ssl.keystore.certificate.chain=${KAFKA_CERT}
spring.kafka.properties.ssl.keystore.key=${KAFKA_KEY}
spring.kafka.properties.ssl.truststore.type=PEM
spring.kafka.properties.ssl.truststore.certificates=${KAFKA_CA}
spring.kafka.properties.ssl.endpoint.identification.algorithm=
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer


logging.level.org.springframework.web=DEBUG
logging.level.com.patientmanage.patientservice=DEBUG
# Server port
server.port=${PORT:4000}

# Logging
logging.level.root=info
