spring.application.name=patient-service
# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://patient-service-db:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer


logging.level.org.springframework.web=DEBUG
logging.level.com.patientmanage.patientservice=DEBUG
# Server port
server.port=4000

# Logging
logging.level.root=info
